/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rticonnector_RTIDDSConnector */

#ifndef _Included_rticonnector_RTIDDSConnector
#define _Included_rticonnector_RTIDDSConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rticonnector_RTIDDSConnector
 * Method:    RTIDDSConnector_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_rticonnector_RTIDDSConnector_RTIDDSConnector_1new
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
