/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RTIDDSConnector */

#ifndef _Included_RTIDDSConnector
#define _Included_RTIDDSConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RTIDDSConnector
 * Method:    RTIDDSConnector_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_RTIDDSConnector_RTIDDSConnector_1new
  (JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
