/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rticonnector;

import org.junit.Test;
import static org.junit.Assert.*;

public class RTIDDSConnectorTest {
    @Test public void testCreate() {
        RTIDDSConnector classUnderTest = new RTIDDSConnector();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
